name: Java CI with Gradle on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Build with Gradle
        run: gradle clean test
      - name: Install Allure
        run: |
          sudo apt-add-repository -y ppa:qameta/allure
          sudo apt-get update
          sudo apt-get install -y allure
      - name: Generate Allure Report
        run: |
          allure generate --clean
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          publish_dir: allure-report
