name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install Chrome
        run: |
          brew cask install google-chrome
      - name: Build with Gradle
        run: gradle clean test
      - name: Install Allure
        run: |
          brew install allure
      - name: Generate Allure Report
        run: |
          allure serve allure-results
      - name: Prepare Report Directory
        run: |
          mkdir -p report/allure-results
          cp -r build/allure-results/* report/allure-results
      - name: Deploying to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          publish_dir: report
